### ISSUE TITLE
Grid content not responding properly?

### ISSUE THREAD

**Issue by Sk16ck** [Sk16ck/modularity-mindfulness#1]
Whenever I try to centre content using the class grid-middle it doesn't respond properly. That or I am not using the content properly and unaware.

@charlie-quinn

**Comment by charlie-quinn** [comment]
@Sk16ck I took a peek at your code, but before I can help with your overall grid setup:
- [ ] try writing out all of the HTML first to help decide where to put the `<div>` tags and `grid, unit, etc` classes *(lookup what each of these classes is doing to your code for a better understanding of their role)*
- [ ] starting point: wrap everything inside of your header with a `<div>` and add the `grid grid-middle wrapper` classes
  - [ ] wrap your `<h1>` inside of a `<div>` and add the `logo unit xs-1 s-1 m-1 l-1-4 pad-t-1-2 pad-b-1-2 gutter-1-4` classes *(lookup what each of these classes is doing to your code for a better understanding of their role)*
  - [ ] add the `unit` and other relevant sizing classes to your `<nav>`

**Comment by charlie-quinn** [comment]
Hey @Sk16ck don't forget to close this issue once it's been resolved! ✅
