### ISSUE TITLE
Content Checklist

### ISSUE THREAD

**Issue by Sk16ck** [Sk16ck/modularity-mindfulness#2]
I was asked to create an issue for a content checklist that needs to be done. Thanks for the help.

@charlie-quinn

**Comment by charlie-quinn** [comment]
- [ ] inside of the "Symbolism" block, remove the `.gutter-1-4` class on the container `<div>`

I'll give you the footer since you've already done the hard part for this assignment.
Footer Content:
  `<footer class="pad-t-1-2 pad-b-1-2 gutter-1-2" role="contentinfo">`
    `<small class="micro">© 794 Heian Period</small>`
  `</footer>`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
